import socket
ip_server = socket.gethostbyname(socket.gethostname())
server_port = 5000
SIZE = 1024
FORMAT = 'utf-8'

LOGIN = '[LOGIN]'
UPDATE_MSG = '[UPDATE USER]'
UPDATE_ACK = '[ATUALIZAÇÃO BEM SUCEDIDA]'
DISCONNECT_MSG = '[DISCONNECT]'
FORCED_DISCONNECTION_MSG = '[FORCED DISCONNECTION]'
TRY_AGAIN = '[TRY AGAIN]'
NEW_REGISTER_MSG = '[REGISTER]'
REGISTRATION_SUCCESS_MSG = '[SUCESSO NO REGISTRO]'
REGISTRATION_FAILED_MSG = '[FALHA DE REGISTRO]'
USER_NOT_FOUND_MSG = '[FALHA NA CONSULTA]'
WRONG_OPTION = '[WRONG OPTION]'
USER_QUERY_MSG = '[USER_QUERY]'

PEER_CALL_REQUEST = '[PEER CALL REQUEST]'
SERVER_CALL_ACK = '[SERVER ACK]'
SERVER_CALL_NACK = '[SERVER NACK]'