import socket
ip_server = '25.64.198.39'
server_port = 5000
SIZE = 1024
FORMAT = 'utf-8'

DISCONNECT_MSG = '[DISCONNECT]'
FORCED_DISCONNECTION_MSG = '[FORCED DISCONNECTION]'
NEW_REGISTER_MSG = '[REGISTER]'
REGISTRATION_SUCCESS_MSG = '[SUCESSO NO REGISTRO]'
REGISTRATION_FAILED_MSG = '[FALHA DE REGISTRO]'
USER_NOT_FOUND_MSG = '[FALHA NA CONSULTA]'
WRONG_OPTION = '[WRONG OPTION]'
USER_QUERY_MSG = '[USER_QUERY]'